#!/bin/python3

# sample Input
# 5 3
# 1 2 100
# 2 5 100
# 3 4 100
import operator
import sys

if __name__ == "__main__":
    n, m = input().strip().split(' ')
    n, m = [int(n), int(m)]


    def ret0(x):
        return 0


    finalList = list(map(ret0, range(n)))

    for a0 in range(m):
        a, b, k = input().strip().split(' ')
        a, b, k = [int(a), int(b), int(k)]
        # print(a,b,k)

        # print(list(operator.add(k, x) for x in finalList[a - 1:b]))
        finalList[a - 1:b] = list(operator.add(k, x) for x in finalList[a - 1:b])

    print(max(finalList))

    # print(finalList)
